### ISSUE TITLE
Doesn't seem to work on Foundry 0.6.6

### ISSUE THREAD

**Issue by foresto** [Moerill/Layer-Hotkeys#10]
Layer-Hotkeys triggers compatibility warnings on Foundry 0.6.6, and doesn't show any configuration options. Did I miss something?

**Comment by Moerill** [comment]
Compatibility warnings are just there cause i'm to lazy to update, just for avoiding those compatibility warnings.

What you're missing?
https://github.com/Moerill/Layer-Hotkeys#bug-reporting everything listed there

In my testing, and judging from no bug reports before yours, regarding 0.6.6 incompatibility, i am not sure whats wrong on your side though

**Comment by foresto** [comment]
Module version: 1.7.0
FVTT version: 0.6.6
Browser and OS used: Firefox and Chromium on linux

What happened?  Layer Hotkeys didn't show any UI or config module settings or anything else.
What should've happened?  Layer Hotkeys should have shown some sign that it does something or could be configured.

Console errors? (F12 or F11 in most browsers)

    Uncaught (in promise) TypeError: ui.controls.controls is null
        default layer-hotkeys.js:19
        _call foundry.js:2239
        callAll foundry.js:2199
        setupGame foundry.js:5838
        _initializeGameView foundry.js:6469
        initialize foundry.js:5754
        async* foundry.js:6595
        async* foundry.js:6593
    layer-hotkeys.js:19:27

Workflow to recreate the bug: Install Layer Hotkeys, then activate it. Console error appears immediately. (Sorry I missed it the first time.)

**Comment by Moerill** [comment]
and you have no other module installed?
cause ``ui.controls.controls`` being ``null`` should be kinda bad for whole fvtt

**Comment by foresto** [comment]
> and you have no other module installed?

None.

**Comment by Moerill** [comment]
ok ye i found the issue, i think.
Is it possible that you do not have an active scene?

**Comment by Moerill** [comment]
if yes, please try activating a scene, reload and check whether the issue still exists.

**Comment by foresto** [comment]
> Is it possible that you do not have an active scene?

Yes! It was a fresh world; no scenes had been created yet.

After I created a scene, the module config panel started showing up and Layer Hotkeys started working.

**Comment by Moerill** [comment]
thanks for checking!
its kind of an inherent problem of the way i try to generate the available layers automatically.. and having no scene active is kind of a rare case, happening almost only in the case of a newly created game, so i don't think i'll do anything about that resulting in a bug.

**Comment by foresto** [comment]
Would it not make sense to at least document this, so people intending to use Layer Hotkeys to create new worlds are not confused when they find that it doesn't work? I nearly just deleted the module, since it looked exactly like an abandoned nonfunctional project.

**Comment by Moerill** [comment]
I'm always open for pull requests adding documentation or anything.

anyway "abandoned" is partly correct - there is not much to add or change here anymore.
