### ISSUE TITLE
Hotkey are case sensitive.

### ISSUE THREAD

**Issue by EndlesNights** [Moerill/Layer-Hotkeys#3]
Custom hotkeys are case sensitive, if a hotkey is set to a value of "q" it will not trigger if the keyboard key of 'q' is pressed in conjunction with a CapsLock being activated. And conversely, if a hotkey is set to a value of "Q"  it will only trigger if the keyboard key of 'q' is pressed in conjunction with a CapsLock being activated.

**Comment by Moerill** [comment]
yep, this is on purpose.
